Improve the rbsnap script somewhat.

diff --git a/Local/bin/rbsnap b/Local/bin/rbsnap
--- a/Local/bin/rbsnap
+++ b/Local/bin/rbsnap
@@ -4,10 +4,17 @@ set -e
 
 SOURCE=$1
 DEST=$2
-PORT=${3:-22}
+PORT=$3
 HOSTNAME=$(hostname)
 BASEDIR=Backup
 BACKUP=$BASEDIR/$HOSTNAME
+SSH="ssh"
+if [ ! -z "$PORT" ]; then
+  SSH="$SSH -p $PORT"
+fi
+SSH="$SSH -C $DEST"
+
+command -v pv >/dev/null 2>&1 || { echo >&2 "Even though I don't have to require pv I require it anyway :-)? Please install pv. Aborting."; exit 1; }
 
 if [ -z "$SOURCE" ]; then
   echo "No source set (first argument - should be full path)"
@@ -24,13 +31,15 @@ if [ $(stat --format=%i $SOURCE) -ne 256 ]; then
   exit 1
 fi
 
+echo "ssh cmd: $SSH"
+
 if [ ! -e "$SOURCE/.backup-latest" ]; then
   echo "Creating initial snapshot at $SOURCE/.backup-latest"
   sudo btrfs subvolume snapshot -r $SOURCE $SOURCE/.backup-latest
   sync
 fi
 
-if ssh -p $PORT $DEST "test -e $BACKUP/.backup-latest"; then
+if $SSH "test -e $BACKUP/.backup-latest"; then
   echo "Snapshotting $SOURCE to $SOURCE/.backup-new"
   if [ -e $SOURCE/.backup-new ]; then
     sudo btrfs subvolume delete $SOURCE/.backup-new
@@ -39,9 +48,9 @@ if ssh -p $PORT $DEST "test -e $BACKUP/.backup-latest"; then
   sync
   echo "Sending diff between $SOURCE/.backup-latest and $SOURCE/.backup-new to $DEST"
 
-  sudo btrfs send -p $SOURCE/.backup-latest $SOURCE/.backup-new | pv | ssh -p $PORT -C $DEST "sudo btrfs receive $BACKUP"
+  sudo btrfs send -p $SOURCE/.backup-latest $SOURCE/.backup-new | pv | $SSH "sudo btrfs receive $BACKUP"
 
-ssh -p $PORT $DEST << EOF
+$SSH << EOF
 sync
 
 echo "Deleting old backup $BACKUP/.backup-latest..."
@@ -54,12 +63,12 @@ EOF
 else
   echo "Sending initial snapshot to $DEST:$BACKUP since no preexisting snapshot was found"
 
-ssh -p $PORT -C $DEST << EOF
+$SSH << EOF
 sudo btrfs subvolume create $BASEDIR || true
 sudo btrfs subvolume create $BACKUP || true
 EOF
 
-sudo btrfs send $SOURCE/.backup-latest | pv | ssh -p $PORT -C $DEST "sudo btrfs receive $BACKUP"
+sudo btrfs send $SOURCE/.backup-latest | pv | $SSH "sudo btrfs receive $BACKUP"
 
 fi
 
